apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nova-ca-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  refreshInterval: "1h"

  target:
    creationPolicy: Owner
    deletionPolicy: Retain

    template:
      type: kubernetes.io/tls

  dataFrom:
    - extract:
        key: rosa-ag/services/cert-manager/nova-ca-tls