apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nova-wiki-db
  labels:
    app.kubernetes.io/part-of: nova-wiki
spec:
  instances: 1

  backup:
    barmanObjectStore:
      destinationPath: s3://rosa-nova-core/cnpg/backups/
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: aws-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: aws-creds
        sessionToken:
          key: ACCESS_SESSION_TOKEN
          name: aws-creds

  bootstrap:
    initdb:
      database: wiki
      owner: wiki
      secret:
        name: nova-wiki-db-creds

  storage:
    size: 500Mi