apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-nova
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  bootstrap:
    recovery:
      source: keycloak
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-nova-db-creds

  externalClusters:
    - name: keycloak
      barmanObjectStore:
        destinationPath: s3://rosa-nova-core/cnpg/backups/
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY
          sessionToken:
            name: aws-creds
            key: ACCESS_SESSION_TOKEN
        wal:
          maxParallel: 8

  storage:
    size: 1Gi