apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-nova-db-creds
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  refreshInterval: "1h"

  target:
    creationPolicy: Owner
    deletionPolicy: Retain

  dataFrom:
    - extract:
        key: rosa/nova-core/services/keycloak/keycloak-nova-db-creds