apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-nova
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::248503644949:role/rosa-nova-core-cnpg

  bootstrap:
    recovery:
      source: keycloak
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-nova-db-creds

  externalClusters:
    - name: keycloak
      barmanObjectStore:
        destinationPath: s3://rosa-nova-core/cnpg/backups/
        s3Credentials:
          inheritFromIAMRole: true
        wal:
          maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: s3://rosa-nova-core/cnpg/backups/
      s3Credentials:
        inheritFromIAMRole: true

  storage:
    size: 1Gi