apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak-nova-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: keycloak-nova