apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: nova
spec:
  instances: 3
  db:
    vendor: postgres
    host: keycloak-nova-rw
    usernameSecret:
      name: keycloak-nova-db-creds
      key: username
    passwordSecret:
      name: keycloak-nova-db-creds
      key: password
  http:
    tlsSecret: id-nova-local-tls
  hostname:
    hostname: id.nova.local