apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: nova
spec:
  instances: 2
  db:
    vendor: postgres
    host: keycloak-rw
    usernameSecret:
      name: keycloak-db-creds
      key: username
    passwordSecret:
      name: keycloak-db-creds
      key: password
  # ingress:
  #   className: openshift-default
  http:
    tlsSecret: nova-id-tls
  hostname:
    hostname: id.nova.local