apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nova-wiki-db
  labels:
    app.kubernetes.io/part-of: nova-wiki
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::248503644949:role/rosa-nova-core-cnpg

  bootstrap:
    recovery:
      source: nova-wiki-db-original
      database: wiki
      owner: wiki
      secret:
        name: nova-wiki-db-creds

  externalClusters:
    - name: nova-wiki-db-original
      barmanObjectStore:
        destinationPath: s3://rosa-nova-core/cnpg/backups/
        s3Credentials:
          inheritFromIAMRole: true
        wal:
          maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: s3://rosa-nova-core/cnpg/backups/
      s3Credentials:
        inheritFromIAMRole: true

  storage:
    size: 500Mi