apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nova-wiki-db
  labels:
    app.kubernetes.io/part-of: nova-wiki
spec:
  instances: 1

  bootstrap:
    recovery:
      source: nova-wiki-db
      database: wiki
      owner: wiki
      secret:
        name: nova-wiki-db-creds

  externalClusters:
    - name: nova-wiki-db
      barmanObjectStore:
        destinationPath: s3://rosa-nova-core/cnpg/backups/
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY
          sessionToken:
            name: aws-creds
            key: ACCESS_SESSION_TOKEN
        wal:
          maxParallel: 8

  storage:
    size: 500Mi