namespace: nova-wiki

resources:
  - namespace.yaml
  - db-creds-externalsecret.yaml
  - db-cluster.yaml
  - db-scheduledbackup.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml