namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: rhbk-instance-nova
      finalizers: null
    spec:
      source:
        path:
          gitops/cluster-services/rhbk-operator/instance/overlays/ag