apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
spec:
  instances: 3

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-creds

  storage:
    size: 1Gi