apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: nova-apps
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: nova-apps-tls
  domain: apps.nova.local
  replicas: 1
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal