apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nova-root-ca
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  refreshInterval: "1h"

  target:
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: quay.nova.local
      remoteRef:
        key: rosa-ag/cluster-config/nova-root-ca-cert