apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: nova-apps
  namespace: openshift-ingress-operator
  annotations:
    ingress.operator.openshift.io/auto-delete-load-balancer: "true"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
spec:
  defaultCertificate:
    name: apps-nova-local-tls
  domain: apps.nova.local
  replicas: 2
  logging:
    access:
      destination:
        type: Container
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: Internal
      dnsManagementPolicy: Unmanaged