apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
  - hostname: console.os.nova.local
    name: console
    namespace: openshift-console
    servingCertKeyPairSecret:
      name: console-os-nova-local-tls