apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-os-nova-local
spec:
  secretName: console-os-nova-local-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager

  dnsNames:
    - console.os.nova.local

  issuerRef:
    name: nova-ca
    kind: ClusterIssuer