namespace: cert-manager

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: nova-ca-tls
    spec:
      dataFrom:
        - extract:
            key: rosa/nova-core/services/cert-manager/intermediate-ca