apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: nova
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-rw
    usernameSecret:
      name: keycloak-db-creds
      key: username
    passwordSecret:
      name: keycloak-db-creds
      key: password
  http:
    tlsSecret: nova-id-tls
  hostname:
    hostname: id.nova.local