namespace: openshift-gitops

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: custom-component-routes
    spec:
      source:
        path: gitops/cluster-config/custom-component-routes/overlays/ag